"""Regenerate REGISTRY.md + registry.json from the backgrounds/ tree.

Scans ``backgrounds/<name>/<name>.meta.json`` for every directory that
holds a ``W_A.npy`` and produces a human-readable registry plus a
machine-readable JSON.

Run after every new fit::

    python scripts/index_backgrounds.py
"""
from __future__ import annotations

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
BG_ROOT = REPO_ROOT / "backgrounds"

logger = logging.getLogger("index_backgrounds")


def _safe_shape(p: Path) -> tuple[int, ...] | None:
    if not p.is_file():
        return None
    try:
        return tuple(np.load(p, mmap_mode="r").shape)
    except Exception:
        return None


def _scan_one(bg_dir: Path) -> dict | None:
    w = bg_dir / "W_A.npy"
    if not w.is_file():
        return None
    meta_files = list(bg_dir.glob("*.meta.json"))
    meta: dict = {}
    if meta_files:
        try:
            meta = json.loads(meta_files[0].read_text())
        except Exception:
            pass
    W_shape = _safe_shape(w)
    mu_shape = _safe_shape(bg_dir / "mu_A.npy")
    eig_shape = _safe_shape(bg_dir / "eigvals_A.npy")
    diag = meta.get("diagnostics") or {}
    dim = meta.get("embedding_dim") or (W_shape[0] if W_shape else None)
    return {
        "name": meta.get("name") or bg_dir.name,
        "dim": dim,
        "embedding_model": meta.get("embedding_model"),
        "provider": meta.get("provider"),
        "max_chars_per_doc": meta.get("max_chars_per_doc"),
        "language": meta.get("language"),
        "created_at": meta.get("created_at"),
        "n_fit": diag.get("n_total") or meta.get("n_sample"),
        "rank_full": diag.get("rank_full_eigvals"),
        "rank_deficient": diag.get("rank_deficient_eigvals")
            or meta.get("rank_deficient_eigvals"),
        "top_ev_ratio_pre": diag.get("top_ev_ratio_pre")
            or meta.get("top_ev_ratio_pre"),
        "eigvals_max": diag.get("eigvals_max"),
        "eigvals_min": diag.get("eigvals_min"),
        "fit_s": diag.get("fit_s"),
        "embedding_cost_usd": (meta.get("embedding_cost") or {}).get("cost_usd"),
        "embedding_tokens": (meta.get("embedding_cost") or {}).get("prompt_tokens"),
        "corpus_fingerprint": meta.get("corpus_fingerprint_sha256"),
        "build_script": meta.get("build_script"),
        "path": f"backgrounds/{bg_dir.name}",
        "W_shape": list(W_shape) if W_shape else None,
        "mu_shape": list(mu_shape) if mu_shape else None,
        "eigvals_shape": list(eig_shape) if eig_shape else None,
        "size_bytes": sum(
            (bg_dir / f).stat().st_size
            for f in ("W_A.npy", "mu_A.npy", "eigvals_A.npy")
            if (bg_dir / f).is_file()
        ),
    }


def _fmt_size(n: int | None) -> str:
    if not n:
        return "—"
    n = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f} {unit}"
        n /= 1024.0
    return f"{n:.1f} TB"


def _fmt_ts(s: str | None) -> str:
    if not s:
        return "—"
    try:
        return datetime.fromisoformat(s.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return s[:16]


def _fmt_cap(v) -> str:
    return "no cap" if v in (None, 0) else f"{v} chars"


def render_md(records: list[dict]) -> str:
    lines = [
        "# siteFocus whitening backgrounds — registry",
        "",
        "Auto-generated by `scripts/index_backgrounds.py`. Regenerate after",
        "every new fit. Do not hand-edit.",
        "",
        f"Last scanned: **{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}**  ·  "
        f"backgrounds: **{len(records)}**",
        "",
        "## Available backgrounds",
        "",
        "| Name | Model | Dim | Cap | N fit | Rank def. | Top eig / mean | Size | Cost | Built |",
        "|---|---|---:|---|---:|---:|---:|---:|---:|---|",
    ]
    recs = sorted(records, key=lambda r: (r.get("embedding_model") or "",
                                          r.get("dim") or 0, r.get("name") or ""))
    for r in recs:
        ratio = f"{r['top_ev_ratio_pre']:.1f}" if r.get("top_ev_ratio_pre") else "—"
        rank_def = r.get("rank_deficient")
        rank_def_s = f"{rank_def}" if rank_def is not None else "—"
        cost = r.get("embedding_cost_usd")
        cost_s = f"${cost:.2f}" if isinstance(cost, (int, float)) else "—"
        lines.append(
            f"| `{r['name']}` "
            f"| `{r.get('embedding_model') or '—'}` "
            f"| {r.get('dim') or '?'} "
            f"| {_fmt_cap(r.get('max_chars_per_doc'))} "
            f"| {r.get('n_fit') or '?'} "
            f"| {rank_def_s} "
            f"| {ratio} "
            f"| {_fmt_size(r.get('size_bytes'))} "
            f"| {cost_s} "
            f"| {_fmt_ts(r.get('created_at'))} |"
        )
    lines += ["", "## Details", ""]
    for r in recs:
        ratio = f"{r['top_ev_ratio_pre']:.1f}" if r.get("top_ev_ratio_pre") else "—"
        block = [
            f"### `{r['name']}`",
            "",
            f"- **path:** `{r['path']}`",
            f"- **model:** `{r.get('embedding_model') or '—'}`"
            + (f" (via {r['provider']})" if r.get("provider") else ""),
            f"- **dim:** {r.get('dim')}",
            f"- **char cap:** {_fmt_cap(r.get('max_chars_per_doc'))}",
            f"- **shapes:** W={r.get('W_shape')}  ·  mu={r.get('mu_shape')}  ·  eigvals={r.get('eigvals_shape')}",
            f"- **N fit:** {r.get('n_fit') or '?'}  ·  rank full/def.: {r.get('rank_full')} / {r.get('rank_deficient')}",
            f"- **top_ev_ratio (pre-whitening anisotropy):** {ratio}",
        ]
        if r.get("eigvals_min") is not None:
            block.append(
                f"- **eigvals range:** min={r['eigvals_min']:.3e}  ·  max={r['eigvals_max']:.3e}"
            )
        if r.get("embedding_cost_usd") is not None:
            block.append(
                f"- **embedding cost:** ${r['embedding_cost_usd']:.4f}  ·  "
                f"tokens={r.get('embedding_tokens'):,}"
            )
        if r.get("fit_s"):
            block.append(f"- **fit wall:** {r['fit_s']} s")
        block += [
            f"- **built:** {_fmt_ts(r.get('created_at'))}  ·  by `{r.get('build_script') or '?'}`",
        ]
        if r.get("corpus_fingerprint"):
            block.append(f"- **corpus fingerprint:** `{r['corpus_fingerprint'][:16]}…`")
        block.append("")
        lines += block
    return "\n".join(lines)


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    records: list[dict] = []
    if BG_ROOT.is_dir():
        for d in sorted(BG_ROOT.iterdir()):
            if d.is_dir():
                rec = _scan_one(d)
                if rec:
                    records.append(rec)
    (REPO_ROOT / "registry.json").write_text(
        json.dumps({"backgrounds": records}, indent=2, ensure_ascii=False)
    )
    (REPO_ROOT / "REGISTRY.md").write_text(render_md(records))
    logger.info("indexed %d backgrounds → REGISTRY.md + registry.json",
                len(records))
    return 0


if __name__ == "__main__":
    sys.exit(main())
